id: P006872
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:27:48.963338
source_metadata:
  id: bdr:W26041
  title: དཀར་རྩིས་དང་ནག་རྩིས་ཀྱི་གཞུང་།
  author: ''
  volumes:
    073112d265c4427b8a572efef30c05da:
      image_group_id: I1KG11905
      title: ''
      volume_number: 1
      total_pages: 608
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
